const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.TextBox,
		C3.Plugins.LocalStorage,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Behaviors.shadowcaster,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Cnds.IsVisible,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Exps.ItemValue
	];
};
self.C3_JsPropNameTable = [
	{поп: 0},
	{backgroundPOP: 0},
	{вфівфцвфі: 0},
	{Variable1: 0},
	{w1: 0},
	{w2: 0},
	{Touch: 0},
	{Keyboard: 0},
	{TextInput2: 0},
	{LocalStorage: 0},
	{images: 0},
	{Карточка: 0},
	{Менеджера: 0},
	{ChatGPTImage15Січ2026Р14_05_: 0},
	{ChatGPTImage15Січ2026Р14_07_: 0},
	{ChatGPTImage15Січ2026Р14_07_2: 0},
	{БезНазви: 0},
	{БезНазви2: 0},
	{Sprite: 0},
	{віфвфів: 0},
	{idButton: 0},
	{імідж: 0},
	{ТоварнийЗапас: 0},
	{фіввфів: 0},
	{фіввфів2: 0},
	{фівфів: 0},
	{БезНазви3: 0},
	{БезНазви4: 0},
	{БезНазви5: 0},
	{вфівфівфів: 0},
	{фівфів2: 0},
	{вфцвфцвфі: 0},
	{БезНазви6: 0},
	{TextInput: 0},
	{імідж2: 0},
	{Fade: 0},
	{Tween: 0},
	{ShadowCaster: 0},
	{images2: 0},
	{Sprite2: 0},
	{numLine: 0},
	{numCalc: 0},
	{name: 0},
	{firtstGame: 0},
	{textLine0: 0},
	{textLine1: 0},
	{textLine2: 0},
	{textLine3: 0},
	{textLine4: 0},
	{textLine5: 0},
	{textLine6: 0},
	{textLine7: 0},
	{textLine8: 0}
];

self.InstanceType = {
	поп: class extends self.ISpriteInstance {},
	backgroundPOP: class extends self.ISpriteInstance {},
	вфівфцвфі: class extends self.ISpriteInstance {},
	w1: class extends self.ISpriteInstance {},
	w2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	TextInput2: class extends self.ITextInputInstance {},
	LocalStorage: class extends self.IInstance {},
	images: class extends self.ISpriteInstance {},
	Карточка: class extends self.ITextInstance {},
	Менеджера: class extends self.ITextInstance {},
	ChatGPTImage15Січ2026Р14_05_: class extends self.ISpriteInstance {},
	ChatGPTImage15Січ2026Р14_07_: class extends self.ISpriteInstance {},
	ChatGPTImage15Січ2026Р14_07_2: class extends self.ISpriteInstance {},
	БезНазви: class extends self.ISpriteInstance {},
	БезНазви2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	віфвфів: class extends self.ISpriteInstance {},
	імідж: class extends self.ITextInstance {},
	ТоварнийЗапас: class extends self.ITextInstance {},
	фіввфів: class extends self.ISpriteInstance {},
	фіввфів2: class extends self.ISpriteInstance {},
	фівфів: class extends self.ISpriteInstance {},
	БезНазви3: class extends self.ISpriteInstance {},
	БезНазви4: class extends self.ISpriteInstance {},
	БезНазви5: class extends self.ISpriteInstance {},
	вфівфівфів: class extends self.ISpriteInstance {},
	фівфів2: class extends self.ISpriteInstance {},
	вфцвфцвфі: class extends self.ISpriteInstance {},
	БезНазви6: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	імідж2: class extends self.ITextInstance {},
	images2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {}
}